//Create Adventure Notifier Class - part of riverpod implementation
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../shared/models/date_range_model.dart';
import '../../../shared/models/location_model.dart';
import '../domain/models/adventure_model.dart';
import 'adventure_providers.dart';
import 'create_adventure_state.dart';

class CreateAdventureNotifer extends Notifier<CreateAdventureState> {
  @override
  CreateAdventureState build() {
    return CreateAdventureState();
  }

  Future<void> createAdventure({
    required String userId,
    required LocationModel location,
    required DateRangeModel dateRange,
    required AdventureType type,
    required String description,
    required int maxPeople,
  }) async {
    state = state.copyWith(isLoading: true, error: null);
    try {
      final repository = ref.read(adventureRepositoryProvider);

      final newAdventure = Adventure(
        id: '', // Will be generated by backend
        userId: userId,
        location: location,
        dateRange: dateRange,
        type: type,
        description: description,
        maxPeople: maxPeople,
      );
      final createdAdventure = await repository.createAdventure(newAdventure);
      //fetched the created adventure
      state = state.copyWith(
        isLoading: false,
        createdAdventure: createdAdventure,
      );
      ref.invalidate(adventureProvider);
    } catch (error) {
      state = state.copyWith(isLoading: false, error: error.toString());
    }
  }

  //todo what is this
  void resetState() {
    state = CreateAdventureState();
  }
}
